[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "GX3RZ3xnw3qSrfAc8KSmmWEgCB4zSvyisqWyiwJXvtEi"

[programs.devnet]
hello_world = "GX3RZ3xnw3qSrfAc8KSmmWEgCB4zSvyisqWyiwJXvtEi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/outsider/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
