[toolchain]

[features]
seeds = false
skip-lint = false

# [programs.localnet]
# contract_creator = "6zv3mCftMCeXkxhsyFEFXYWEiW5rqrBjJ8CChrZ9rY6w"

[programs.devnet]
contract_creator = "6zv3mCftMCeXkxhsyFEFXYWEiW5rqrBjJ8CChrZ9rY6w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# wallet = "/home/outsider/.config/solana/id.json"
wallet = "/Users/victor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
